NMD-440 Added new get methods and tests for them, refactored update methods
Glipchik/SecondMap pull request #21
Opened 2023-08-02 06:45 UTC by glebtyanov

2023-08-02 08:11 UTC, Glipchik requested changes

2023-08-02 08:11 UTC, Glipchik commented on SecondMap.Services.SMS/SecondMap.Services.SMS.UnitTests/Tests/Validators/Reviews/ReviewsUpdateValidatorTests.cs
> +			// Arrange
Remove

2023-08-02 08:33 UTC, moltenessence commented on SecondMap.Services.SMS/SecondMap.Services.SMS.BLL/Services/ScheduleService.cs
> +			if (!foundSchedules.Any())
Isn't it better from the point of business logic and performance just to return empty collection and not to throw exception?

2023-08-02 08:33 UTC, moltenessence commented on SecondMap.Services.SMS/SecondMap.Services.SMS.BLL/Services/StoreService.cs
> +				Log.Error("Store with id = {@id} not found", id);
Same

2023-08-02 08:33 UTC, moltenessence commented on SecondMap.Services.SMS/SecondMap.Services.SMS.IntegrationTests/Tests/ReviewControllerTests.cs
> +				await _client.GetAsync(TestConstants.REVIEWS_URL + "/" + ApiEndpoints.STORE_ID_EQUALS + $"{invalidId}");
Implement path builder

2023-08-02 08:43 UTC, glebtyanov commented on SecondMap.Services.SMS/SecondMap.Services.SMS.BLL/Services/ScheduleService.cs
> +			if (!foundSchedules.Any())
ye, totally agree. thx

2023-08-02 09:04 UTC, glebtyanov commented on SecondMap.Services.SMS/SecondMap.Services.SMS.IntegrationTests/Tests/ReviewControllerTests.cs
> +				await _client.GetAsync(TestConstants.REVIEWS_URL + "/" + ApiEndpoints.STORE_ID_EQUALS + $"{invalidId}");
I'l make a separate pr to refactor tests later

2023-08-02 13:49 UTC, Glipchik approved these changes

2023-08-04 05:34 UTC, Genresal approved these changes

2023-08-04 05:40 UTC, merged