NMD-437 Database and identity configs for identity server
Glipchik/SecondMap pull request #26
Opened 2023-08-24 07:37 UTC by glebtyanov

Authorization logic will be in separate pr

2023-08-25 09:26 UTC, SasukeVapes requested changes

2023-08-25 09:26 UTC, SasukeVapes commented on SecondMap.Services.Auth/SecondMap.Services.Auth.Infrastructure/Configurations/IdentityConfiguration.cs
> +					RedirectUris = { "https://localhost:5002/signin-oidc" },
`RedirectUris = { "https://localhost:5002/signin-oidc" },`
 It's better to use configuration values for URLs, not hardcoded strings

2023-08-25 09:26 UTC, SasukeVapes commented on SecondMap.Services.Auth/SecondMap.Services.Auth.Infrastructure/Extensions/ServiceCollectionExtensions.cs
> +				authDbContext.SaveChangesAsync().GetAwaiter().GetResult();
`.GetAwaiter().GetResult();`
Who told u to do so? this can lead to deadlocks. Just use async/await consistently

2023-08-28 08:35 UTC, Genresal approved these changes

2023-08-28 08:35 UTC, merged