NMD-413 Split dtos to entities, models, viewmodels
Glipchik/SecondMap pull request #8
Opened 2023-07-20 12:35 UTC by glebtyanov

2023-07-20 13:42 UTC, Glipchik requested changes

2023-07-20 13:42 UTC, Glipchik commented on SecondMap.Services.StoreManagementService/SecondMap.Services.StoreManagementService.BLL/Services/ReviewService.cs
> +			return _mapper.Map<List<Review>>(await _repository.GetAllAsync());
Is it possible to use more abstract collection (i.e. IEnumerable, IQuerable, IList)?

2023-07-20 13:42 UTC, Glipchik commented on SecondMap.Services.StoreManagementService/SecondMap.Services.StoreManagementService.BLL/Services/ReviewService.cs
>  		public async Task<List<Review>> GetAllAsync()
The same

2023-07-20 13:42 UTC, Glipchik commented on SecondMap.Services.StoreManagementService/SecondMap.Services.StoreManagementService.BLL/Services/ScheduleService.cs
>  		public async Task<List<Schedule>> GetAllAsync()
The same and also in the next examples

2023-07-20 13:42 UTC, Glipchik commented on SecondMap.Services.StoreManagementService/SecondMap.Services.StoreManagementServices.API/Controllers/ReviewsController.cs
>  		[HttpPut("{id}")]
Move strings to constants

2023-07-21 10:44 UTC, Genresal requested changes

2023-07-21 10:44 UTC, Genresal commented on SecondMap.Services.StoreManagementService/SecondMap.Services.StoreManagementServices.API/Controllers/ReviewsController.cs
>  	[ApiController]
Not an issue, but not sure that is necessary, to store routes inside constants. If you think that way then let it be. (some kind of design)

2023-07-21 10:44 UTC, Genresal commented on SecondMap.Services.StoreManagementService/SecondMap.Services.StoreManagementServices.API/Controllers/UsersController.cs
>  		{
losted space between rows

2023-07-21 10:44 UTC, Genresal commented on SecondMap.Services.StoreManagementService/SecondMap.Services.StoreManagementServices.API/Controllers/UsersController.cs
>  		}
possible there need to return created data too, like inside your the "update" endpoint. and inside other controllers too.

2023-07-21 10:44 UTC, Genresal commented on SecondMap.Services.StoreManagementService/SecondMap.Services.StoreManagementServices.API/MappingProfiles/ViewModelsToModelsProfile.cs
> +{
better store all automapper profiles at one place. You can move all your models to separate project

2023-07-21 10:44 UTC, Genresal commented on SecondMap.Services.StoreManagementService/SecondMap.Services.StoreManagementService.BLL/Extensions/ServiceCollectionExtensions.cs
>  		}
Why you have automapper injecting there and at Program.cs, better unite all stuff and inject as one huge piece.

2023-07-21 10:44 UTC, Genresal commented on SecondMap.Services.StoreManagementService/SecondMap.Services.StoreManagementServices.API/ViewModels/StoreViewModel.cs
> +		public decimal Price { get; set; }
why not string.empty, or you can make it nullable

2023-07-21 10:58 UTC, glebtyanov commented on SecondMap.Services.StoreManagementService/SecondMap.Services.StoreManagementServices.API/Controllers/ReviewsController.cs
>  	[ApiController]
@Glipchik recommended to not have any hardcoded strings in the project, maybe I took it bit too far, might change it later

2023-07-21 12:13 UTC, Glipchik approved these changes

2023-07-21 12:14 UTC, Genresal approved these changes

2023-07-21 12:15 UTC, merged